import { render, act } from "@testing-library/react";
import React, { Children, cloneElement, isValidElement } from "react";

/**
 * We use some internals from React to avoid a lot of warnings in our tests when faking
 * to render server components. If the structure of React changes, this function should still work,
 * but the tests will again print warnings.
 *
 * If this is the case, this function can also simply be removed and all tests should still function.
 */
function setFakeReactDispatcher<T>(action: () => T): T {
  /* v8 ignore start */
  if (
    !(
      "__CLIENT_INTERNALS_DO_NOT_USE_OR_WARN_USERS_THEY_CANNOT_UPGRADE" in React
    )
  ) {
    return action();
  }
  /* v8 ignore stop */

  /* v8 ignore start */
  const secret =
    React.__CLIENT_INTERNALS_DO_NOT_USE_OR_WARN_USERS_THEY_CANNOT_UPGRADE;

  if (!secret || typeof secret !== "object" || !("H" in secret)) {
    return action();
  }
  /* v8 ignore stop */

  const previousDispatcher = secret.H;

  try {
    secret.H = new Proxy(
      {},
      {
        get() {
          throw new Error("This is a client component");
        },
      },
    );
    /* v8 ignore start */
  } catch {
    return action();
  }
  /* v8 ignore stop */

  const result = action();

  secret.H = previousDispatcher;

  return result;
}

type ReactElementWithChildren = React.ReactElement<React.PropsWithChildren>;

type ReactNode =
  | ReactElementWithChildren
  | string
  | number
  | bigint
  | ReactNode[]
  | boolean
  | null
  | undefined;

async function evaluateServerComponent(node: ReactNode): Promise<ReactNode> {
  if (node === null) {
    // Case of a component returning null
    return node;
  }

  if (typeof node !== "object") {
    // Case of a component returning a number, a string, undefined
    return node;
  }

  if (!("type" in node)) {
    // Case of a component returning an array, a promise
    return node;
  }

  if (node.type.constructor.name === "AsyncFunction") {
    const func = node.type as (
      props: unknown,
    ) => Promise<ReactElementWithChildren>;

    // Handle async server nodes by calling await
    return evaluateServerComponent(await func(node.props));
  }

  if (node.type.constructor.name === "Function") {
    const func = node.type as (props: unknown) => ReactElementWithChildren;

    try {
      return setFakeReactDispatcher(() =>
        evaluateServerComponent(func(node.props)),
      );
    } catch {
      // If evaluating fails with a function node, it might be because of using client side hooks.
      // Here the errors generated by React 19:
      //
      // > Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
      // > 1. You might have mismatching versions of React and the renderer (such as React DOM)
      // > 2. You might be breaking the Rules of Hooks
      // > 3. You might have more than one copy of React in the same app
      // > See https://react.dev/link/invalid-hook-call for tips about how to debug and fix this problem.
      //
      // > TypeError: Cannot read properties of null (reading 'useState')
      //
      // > TypeError: Cannot read properties of null (reading 'useContext')
      //
      // > TypeError: Cannot read properties of null (reading 'useRef')
      //
      // > TypeError: Cannot read properties of null (reading 'useMemo')
      //
      // > TypeError: Cannot read properties of null (reading 'useEffect')
      //
      // In that case, simply return the node, it will be handled by the react-testing-library render function
    }
  }

  return node;
}

async function evaluateServerComponentAndChildren(
  node: ReactNode,
): Promise<ReactNode> {
  const evaluatedNode = await evaluateServerComponent(node);

  if (evaluatedNode === null) {
    // Case of a component returning null
    return evaluatedNode;
  }

  if (typeof evaluatedNode !== "object") {
    // Case of a component returning a number, a string, undefined
    return evaluatedNode;
  }

  if (!("props" in evaluatedNode)) {
    // Case of a component returning an array
    return evaluatedNode;
  }

  const children = Children.toArray(evaluatedNode.props.children);

  const evaluatePromises = [];

  // As we are trying to limit test timeouts every
  // ms counts which is why we are opting for the
  // faster for (...) {...} loop over .forEach or
  // .map functions
  for (let i = 0; i < children.length; i++) {
    const child = children[i];

    if (!isValidElement(child)) {
      // If element is a string, number, object... React does not consider it as a valid React element
      // > Only JSX tags and objects returned by createElement are considered to be React elements
      evaluatePromises[i] = Promise.resolve(child);
      continue;
    }

    evaluatePromises[i] = evaluateServerComponentAndChildren(
      child as ReactElementWithChildren,
    );
  }

  // By wrapping in Promise.all and evaluating each
  // child we save time by initiating the promises in
  // parallel rather than await-ing each in order.
  const evaluatedChildren = await Promise.all(evaluatePromises);

  // eslint-disable-next-line no-restricted-syntax
  return cloneElement(evaluatedNode, {}, ...evaluatedChildren);
}

/**
 * Flush all pending Suspense boundary resolutions left over after a render.
 *
 * React schedules Suspense re-renders via Promises and Scheduler tasks. Resolving one
 * boundary can reveal another one (a cascade), scheduling further async work that runs after
 * the current act() scope exits.
 *
 * We loop, observing DOM mutations each pass via MutationObserver, until a complete
 * pass produces no mutations — meaning the tree has reached a stable state. This works
 * for any depth of nested Suspense cascade that results in DOM changes.
 *
 * Note: React may still emit "A suspended resource finished loading inside a test" after
 * this loop exits (e.g. when cleanup() unmounts the tree and React's internal Promise
 * tracking fires). That message is suppressed globally in throw-on.setupFiles.ts as it
 * is an inherent artifact of our evaluateServerComponentAndChildren RSC approach, not an
 * actionable signal.
 *
 * FLUSH_MAX_PASSES is a safety guard against infinite loops in pathological cases
 * (e.g. a component that unconditionally mutates the DOM on every render).
 */
const FLUSH_MAX_PASSES = 50;
async function flushSuspenseBoundaries() {
  for (let passes = 1; passes <= FLUSH_MAX_PASSES; passes++) {
    const status = { hasMoreWork: false };
    const observer = new MutationObserver(() => {
      status.hasMoreWork = true;
    });
    observer.observe(document.documentElement, {
      subtree: true,
      childList: true,
      characterData: true,
      attributes: true,
    });
    // Here we are looping on purpose so disable the eslint rule:
    // eslint-disable-next-line no-await-in-loop
    await act(() => Promise.resolve());
    observer.disconnect();

    if (!status.hasMoreWork) return;

    if (passes === FLUSH_MAX_PASSES) {
      throw new Error(
        `flushSuspenseBoundaries failed: Remained unstable after ${FLUSH_MAX_PASSES} passes. ` +
          `This likely indicates an infinite update loop in your components.`,
      );
    }
  }
}

type RenderOptions = Parameters<typeof render>[1];

/**
 * This function is used to render a React component and apply pending React updates, using `act`, before returning the result.
 * This is necessary to ensure that all React updates are applied before we make assertions in our tests.
 */
async function renderResult(
  node: React.ReactNode,
  renderOptions?: RenderOptions,
) {
  const result = await act(() => render(node, renderOptions));

  await flushSuspenseBoundaries();

  return result;
}

/**
 * react-testing-library does not yet support React Server Components.
 * This is the most starred opened issue in react-testing-library GitHub repo.
 *
 * You can read more about React Server Components here: https://react.dev/reference/rsc/server-components
 * Do not confuse RSC with `"use server"` (Server Functions aka Server Actions).
 *
 * A React Server Component doesn't have to be async, but an async component is necessarily a RSC.
 * Here we are talking about _async_ RSC: `async function MyComponent() { await getData(); ... }`.
 *
 * We've created renderWithSuspense() in August 2023 and expected at the time react-testing-library
 * would soon support RSC soon. As of 2025-04, no support yet :-/
 *
 * renderWithSuspense() wraps a given async component in a React Suspense, this is the "official" way:
 * https://github.com/testing-library/react-testing-library/issues/1209#issuecomment-1626333250
 * Suspense works for an entire tree of components by waiting for every async component.
 *
 * Unfortunately, wrapping an async component with Suspense:
 * - Causes the component to re-render 3x times (and thus slow testing), we don't know why (obscure React internals?)
 * - Generates a warning: "async/await is not yet supported in Client Components, only Server Components"
 *   This is a known issue, it's fine and we ignore it in libs/test-runner/throw-on.setupFiles.ts,
 *   see https://github.com/testing-library/react-testing-library/issues/1209#issuecomment-1653724512
 *
 * We tried the other solutions (2025-04) not based on Suspense provided in https://github.com/testing-library/react-testing-library/issues/1209
 * These solutions iterate over a React tree and "manually" wait for every RSC it finds, so the re-renders are minimal.
 * https://gist.github.com/sroebert/a04ca6e0232a4a60bc50d7f164f101f6
 * https://gist.github.com/tarunsahnan/93418e81882f2e343e09894bc6de6f35
 * This function, renderServerComponent(), is based on those solutions.
 *
 * If you have a simple async component without any async child component, use `render(await MyComponent(props))` instead:
 * - The async component will be rendered just once like you expect
 * - You won't have the warning "async/await is not yet supported in Client Components, only Server Components"
 *
 * But, from a "theoretical" point of view, this feels less the way React works by wrapping with Suspense,
 * and if you introduce a child async component in the tree, you will be back to use renderServerComponent().
 *
 * This is an unfortunate situation :-/
 * You can read more in ADR docs/decisions/2024-06-flaky-tests.md
 */
export async function renderServerComponent(
  ui: React.ReactNode | Promise<React.ReactNode>,
  renderOptions?: RenderOptions,
) {
  const node = await ui;

  if (isValidElement(node)) {
    const evaluatedNode = await evaluateServerComponentAndChildren(
      node as ReactNode,
    );

    return renderResult(evaluatedNode, renderOptions);
  }

  return renderResult(node, renderOptions);
}
